export const leagues_dropdown = ['epl', 'seriea', 'ligue1', 'bundesliga', 'laliga'] //# hardcode this

export const fixture_filter = [{'FixtureName': 'Liverpool vs Man City', 'FixtureId': 9999},
                  {'FixtureName': 'Arsenal vs Spurs', 'FixtureId': 9998}] //# from api

export const alpha_table_json = [
    {'EntityName': 'Liverpool vs Man City',
     'Market': 'home_win',
     'CalcProb': 0.6,
     'BookieOdds': 1.9,
     'Alpha': 1.2,
     'KellyCriterion': 2.5,
     'FixtureId': 9999,
     'TeamId': 0},

    {'EntityName': 'Liverpool',
     'Market': 'O1_5',
     'CalcProb': 0.5,
     'BookieOdds': 2.5,
     'Alpha': 1.3,
     'KellyCriterion': 2,
     'FixtureId': 9999,
     'TeamId': 20},

{'EntityName': 'Arsenal vs Spurs',
     'Market': 'home_win',
     'CalcProb': 0.6,
     'BookieOdds': 1.9,
     'Alpha': 1.2,
     'KellyCriterion': 2.5,
     'FixtureId': 9998,
     'TeamId': 0},

    {'EntityName': 'Arsenal',
     'Market': 'O1_5',
     'CalcProb': 0.5,
     'BookieOdds': 2.5,
     'Alpha': 1.3,
     'KellyCriterion': 2,
     'FixtureId': 9998,
     'TeamId': 21}
] //# from api

export const fixture_analysis_table_json = [
    {'TeamName': 'Liverpool',
     'Form': 'WWWWLW',
     'Position': 2,
     'AveragexG': 2,
     'OppositionxGC': 1.5,
     'FixtureId': 9999,
     'TeamId': 20},

    {'TeamName': 'Man City',
     'Form': 'WLWWLD',
     'Position': 4,
     'AveragexG': 2,
     'OppositionxGC': 1.5,
     'FixtureId': 9999,
     'TeamId': 19},

    {'TeamName': 'Arsenal',
     'Form': 'LLLLLW',
     'Position': 20,
     'AveragexG': 1,
     'OppositionxGC': 1.5,
     'FixtureId': 9998,
     'TeamId': 21},
    {'TeamName': 'Spurs',
     'Form': 'DDDWLW',
     'Position': 10,
     'AveragexG': 1.3,
     'OppositionxGC': 1.5,
     'FixtureId': 9998,
     'TeamId': 22}
] //# from api

//# heatmap table
export const goal_probability_heatmap = [
{'FixtureId': 9999,
     'TeamId': 19,
     'TeamName': 'Man City',
     'Zero': 0.15,
     'One': 0.35,
     'Two': 0.25,
     'Three': 0.15,
     'Four': 0.05,
     'Five': 0.01,
     'Six': 0.01},
{'FixtureId': 9999,
     'TeamId': 20,
     'TeamName': 'Liverpool',
     'Zero': 0.15,
     'One': 0.35,
     'Two': 0.25,
     'Three': 0.15,
     'Four': 0.05,
     'Five': 0.01,
     'Six': 0.01},
{'FixtureId': 9998,
     'TeamId': 21,
     'TeamName': 'Arsenal',
     'Zero': 0.15,
     'One': 0.35,
     'Two': 0.25,
     'Three': 0.15,
     'Four': 0.05,
     'Five': 0.01,
     'Six': 0.01},
{'FixtureId': 9998,
     'TeamId': 22,
     'TeamName': 'Spurs',
     'Zero': 0.15,
     'One': 0.35,
     'Two': 0.25,
     'Three': 0.15,
     'Four': 0.05,
     'Five': 0.01,
     'Six': 0.01}
] //# from api
